Revert "vpython: push new version of vpython including fix for proxy propagation."
This reverts commit 932167e4f1e7afa8d19c2951d020dfb099507a30.

Reason for revert: symlink/argv0 handling seems to be broken.

Failure Link: https://ci.chromium.org/b/8677613248508383553

Repro:
$ git clone https://chromium.googlesource.com/chromiumos/chromite
$ ./chromite/run_tests --help
...
ModuleNotFoundError: No module named 'debugpy'

Forcing depot_tools to before this commit works fine again.

Original change's description:
> vpython: push new version of vpython including fix for proxy propagation.
>
> Bug: b/491263752
> Change-Id: I4459e67485bc1b099a477ce4114e199b6a6a6964
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/8017944
> Auto-Submit: Alex Ovsienko <ovsienko@google.com>
> Reviewed-by: Fumitoshi Ukai <ukai@google.com>
> Commit-Queue: Alex Ovsienko <ovsienko@google.com>

Bug: b/491263752
Change-Id: I5cca9f240b4d3c6864e333926212b8586541ef29
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/8025789
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Gavin Mak <gavinmak@google.com>
Commit-Queue: Gavin Mak <gavinmak@google.com>