Revert "Add initial jj support to `gclient sync`."
This reverts commit c7e0383286b03fa38a99cdfe4d36d004990f4931.

Reason for revert:
https://ci.chromium.org/ui/p/infra/builders/try/buildinfra-try-linux/b8692281134183091521/overview
```
In directory: /b/s/w/ir/cache/builder
Traceback (most recent call last):
  File "/b/s/w/ir/kitchen-checkout/depot_tools/gclient.py", line 111, in <module>
    import jj.scm
ModuleNotFoundError: No module named 'jj'
```

Original change's description:
> Add initial jj support to `gclient sync`.
>
> This should be a no-op for most repos with jj.
>
> This is the first step in getting non-colocated repos (jj repos without
> a .git directory - primarily jj workspaces) working with jj.
>
> Bug: b:440949053
> Co-authored by: drubery@chromium.org
>
> Change-Id: I32234d9e37c61f7c2c6a7f0c3b1d9cf96a6a6964
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/7414484
> Reviewed-by: Brian Ryner <bryner@google.com>
> Commit-Queue: Matt Stark <msta@google.com>

Bug: b:440949053, 476863155
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I83bb56bd8f7d0c3e270982c8b9113cc5fbcd3ec5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/7486093
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Owners-Override: Takuto Ikuta <tikuta@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Matt Stark <msta@google.com>
Commit-Queue: Takuto Ikuta <tikuta@chromium.org>